## MODEL TERTUTUP (MASUKKAN-KELUARAN) LEONTIEF

In [ ]:
from sympy import *
import numpy as np

In [ ]:
def add_row(A,k,j,i):
  "Menambahkan k kali baris j ke baris i di matriks A."
  n = A.shape[0]
  E = eye(n)
  if i == j:
      E[i,i]= k+1
  else:
      E[i,j]= k
  return E @ A

def scale_row(A,k,i):
    "Mengalikan angka k ke baris i di matriks A"
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

def switch_rows(A,i,j):
    "Menukar baris i and j di matriks A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A


In [ ]:
#E matriks pertukaran atau matriks masukan-keluaran
E = Matrix([[0.2,0.1,0.6], [0.4, 0.5,0.1],[0.4,0.4,0.3]])
I=  Matrix([[1,0,0],[0,1,0],[0,0,1]])
A= I-E
A

Matrix([
[ 0.8, -0.1, -0.6],
[-0.4,  0.5, -0.1],
[-0.4, -0.4,  0.7]])

In [ ]:
# d vektor 0, karena syarat kesetimbangan:pengeluaran total=pendapatan total
d= Matrix([0,0,0])
Ad = A.row_join(d)
Ad

Matrix([
[ 0.8, -0.1, -0.6, 0],
[-0.4,  0.5, -0.1, 0],
[-0.4, -0.4,  0.7, 0]])

In [ ]:
sol,params= A.gauss_jordan_solve(d)
sol

Matrix([
[0],
[0],
[0]])

Solusi trivial, akan dicari matriks eselon tereduksinya

In [ ]:
Ad= scale_row(Ad,10/8,0)
Ad

Matrix([
[ 1.0, -0.125, -0.75, 0],
[-0.4,    0.5,  -0.1, 0],
[-0.4,   -0.4,   0.7, 0]])

In [ ]:
Ad= add_row(Ad,0.4,0,1)
Ad

Matrix([
[ 1.0, -0.125, -0.75, 0],
[   0,   0.45,  -0.4, 0],
[-0.4,   -0.4,   0.7, 0]])

In [ ]:
Ad= add_row(Ad,0.4,0,2)
Ad

Matrix([
[1.0, -0.125, -0.75, 0],
[  0,   0.45,  -0.4, 0],
[  0,  -0.45,   0.4, 0]])

In [ ]:
Ad= scale_row(Ad,1/0.45,1)
Ad

Matrix([
[1.0, -0.125,              -0.75, 0],
[  0,    1.0, -0.888888888888889, 0],
[  0,  -0.45,                0.4, 0]])

In [ ]:
Ad= add_row(Ad,0.45,1,2)
Ad

Matrix([
[1.0, -0.125,                 -0.75, 0],
[  0,    1.0,    -0.888888888888889, 0],
[  0,      0, -1.11022302462516e-16, 0]])

In [ ]:
Ad= add_row(Ad,0.125,1,0)
Ad

Matrix([
[1.0,   0,    -0.861111111111111, 0],
[  0, 1.0,    -0.888888888888889, 0],
[  0,   0, -1.11022302462516e-16, 0]])

In [ ]:
Ad= scale_row(Ad,1/Ad[2,2],2)
Ad

Matrix([
[1.0,   0, -0.861111111111111, 0],
[  0, 1.0, -0.888888888888889, 0],
[  0,   0,                1.0, 0]])

Dari bentuk matriks eselon tereduksi diatas, dapat dibentuk vektor harga

 [p1,p2,p3]=s[0.861111111111111,0.888888888888889,1].

 Jika kita substitusi harga/gaji tukang ledeng(x3=108), maka s=108





In [ ]:
s = 108
P=Matrix([[0.861111111111111,0.888888888888889,1]])
P*s

Matrix([[93.0, 96.0, 108]])

Dengan dekomposisi

In [ ]:
import numpy as np

# Definisikan matriks A
A = np.array([[ 0.8, -0.1, -0.6],
       [-0.4,  0.5, -0.1],
       [-0.4, -0.4,  0.7]])

# Lakukan SVD pada matriks A
U, S, VT = np.linalg.svd(A)

# Matriks diagonal dari nilai singular dalam bentuk vektor
# Hasil SVD berupa U, nilai singular dalam bentuk diagonal dalam S, dan VT (V Transpose)
print("Matriks U:")
print(U)
print("\nMatriks Singular Values:")
print(np.diag(S))
print("\nMatriks V Transpose:")
print(VT)

#Setelah dilakukan SVD, temukan nilai-nilai singular yang mendekati nol
tolerance = 1e-10  # Ambang batas untuk nilai-nilai yang dianggap nol

# Cek nilai-nilai singular yang mendekati nol
zero_singular_values = np.where(S < tolerance)[0]
# Temukan vektor-vektor non-trivial dari matriks VT (V transpos)
if len(zero_singular_values) > 0:
    non_trivial_solution = VT[zero_singular_values[0]]
    print("Solusi non-trivial ditemukan:")
    print(abs(non_trivial_solution))
else:
    print("Tidak ada solusi non-trivial untuk Ax = 0.")

Matriks U:
[[-0.76594976  0.28282084  0.57735027]
 [ 0.13804485 -0.80474237  0.57735027]
 [ 0.62790491  0.52192153  0.57735027]]

Matriks Singular Values:
[[1.28051219e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.74782900e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.97085221e-17]]

Matriks V Transpose:
[[-0.71779068 -0.08242371  0.69136305]
 [ 0.43803884 -0.82529168  0.35639249]
 [-0.54120099 -0.55865908 -0.62849147]]
Solusi non-trivial ditemukan:
[0.54120099 0.55865908 0.62849147]


In [ ]:
#cek
A_remake = (U @ np.diag(S) @ VT)
print(A_remake)

[[ 0.8 -0.1 -0.6]
 [-0.4  0.5 -0.1]
 [-0.4 -0.4  0.7]]


In [ ]:
P=Matrix([[0.54120099,0.55865908,0.62849147]])
S=108/0.62849147
P*S

Matrix([[93.0000003341334, 95.9999992362665, 108.0]])

Didapat hasil yang sama baik dengan cara gauss jordan (mencari matriks eselon tereduksi) ataupun dengan dekomposisi


#TEOREMA 11.9.1
Jika E adalah sebuah matriks pertukaran, maka Ep=p selalu mempunyai solusi nontrivial p dimana entri-entrinya adalah tak negatif.

In [ ]:
E=Matrix([[1/2,0],[-1/2,0]])
I=Matrix([[1,0],[0,1]])
A= I-E
A

Matrix([
[0.5, 0],
[0.5, 1]])

In [ ]:
#E matriks pertukaran atau matriks masukan-keluaran
E = np.array([[1/2,0],[-1/2,0]])
# Matriks identitas
I = np.eye(len(E))
A=I-E
print(A)

[[0.5 0. ]
 [0.5 1. ]]


In [ ]:
import numpy as np

# Definisikan matriks A
A = np.array([[1/2,0],[-1/2,0]])

# Lakukan SVD pada matriks A
U, S, VT = np.linalg.svd(A)

# Matriks diagonal dari nilai singular dalam bentuk vektor
# Hasil SVD berupa U, nilai singular dalam bentuk diagonal dalam S, dan VT (V Transpose)
print("Matriks U:")
print(U)
print("\nMatriks Singular Values:")
print(np.diag(S))
print("\nMatriks V Transpose:")
print(VT)

#Setelah dilakukan SVD, temukan nilai-nilai singular yang mendekati nol
tolerance = 1e-10  # Ambang batas untuk nilai-nilai yang dianggap nol

# Cek nilai-nilai singular yang mendekati nol
zero_singular_values = np.where(S < tolerance)[0]

# Temukan vektor-vektor non-trivial dari matriks VT (V transpos)
if len(zero_singular_values) > 0:
    non_trivial_solution = VT[zero_singular_values[0]]
    print("Solusi non-trivial ditemukan:")
    print(abs(non_trivial_solution))
else:
    print("Tidak ada solusi non-trivial untuk Ax = 0.")

Matriks U:
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]

Matriks Singular Values:
[[0.70710678 0.        ]
 [0.         0.        ]]

Matriks V Transpose:
[[-1. -0.]
 [ 0.  1.]]
Solusi non-trivial ditemukan:
[0. 1.]


In [ ]:
import numpy as np

# Definisikan matriks A
A = np.array([[0,0],[0,0]])

# Lakukan SVD pada matriks A
U, S, VT = np.linalg.svd(A)

# Matriks diagonal dari nilai singular dalam bentuk vektor
# Hasil SVD berupa U, nilai singular dalam bentuk diagonal dalam S, dan VT (V Transpose)
print("Matriks U:")
print(U)
print("\nMatriks Singular Values:")
print(np.diag(S))
print("\nMatriks V Transpose:")
print(VT)

#Setelah dilakukan SVD, temukan nilai-nilai singular yang mendekati nol
tolerance = 1e-10  # Ambang batas untuk nilai-nilai yang dianggap nol

# Cek nilai-nilai singular yang mendekati nol
zero_singular_values = np.where(S < tolerance)[0]

# Temukan vektor-vektor non-trivial dari matriks VT (V transpos)
if len(zero_singular_values) > 0:
    non_trivial_solution = VT[zero_singular_values[0]]
    print("Solusi non-trivial ditemukan:")
    print(abs(non_trivial_solution))
else:
    print("Tidak ada solusi non-trivial untuk Ax = 0.")

Matriks U:
[[1. 0.]
 [0. 1.]]

Matriks Singular Values:
[[0. 0.]
 [0. 0.]]

Matriks V Transpose:
[[1. 0.]
 [0. 1.]]
Solusi non-trivial ditemukan:
[1. 0.]


In [ ]:
import numpy as np

# Definisikan matriks A
A = np.array([[0,0],[0,0]])

# Lakukan SVD pada matriks A
U, S, VT = np.linalg.svd(A)

# Matriks diagonal dari nilai singular dalam bentuk vektor
# Hasil SVD berupa U, nilai singular dalam bentuk diagonal dalam S, dan VT (V Transpose)
print("Matriks U:")
print(U)
print("\nMatriks Singular Values:")
print(np.diag(S))
print("\nMatriks V Transpose:")
print(VT)

#Setelah dilakukan SVD, temukan nilai-nilai singular yang mendekati nol
tolerance = 1e-10  # Ambang batas untuk nilai-nilai yang dianggap nol

# Cek nilai-nilai singular yang mendekati nol
zero_singular_values = np.where(S < tolerance)[0]

# Temukan vektor-vektor non-trivial dari matriks VT (V transpos)
if len(zero_singular_values) > 0:
    non_trivial_solution = VT[zero_singular_values[1]]
    print("Solusi non-trivial ditemukan:")
    print(abs(non_trivial_solution))
else:
    print("Tidak ada solusi non-trivial untuk Ax = 0.")

Matriks U:
[[1. 0.]
 [0. 1.]]

Matriks Singular Values:
[[0. 0.]
 [0. 0.]]

Matriks V Transpose:
[[1. 0.]
 [0. 1.]]
Solusi non-trivial ditemukan:
[0. 1.]


#TEOREMA 11.9.2

In [ ]:
import numpy as np

# Definisikan matriks input-output Leontief E (pastikan ukuran dan isinya relevan)
E = np.array([[0.2,0.1,0.6], [0.4, 0.5,0.1],[0.4,0.4,0.3]])

# Matriks identitas
I = np.eye(len(E))

# Matriks (I - E)
I_minus_E = I - E

# Hitung nilai-nilai eigen dan vektor-vektor eigen dari matriks (I - E)
eigenvalues, eigenvectors = np.linalg.eig(I_minus_E)

# Temukan vektor eigen yang terkait dengan nilai eigen nol
zero_eigen_vector = eigenvectors[:, np.isclose(eigenvalues, 0)]

# Cetak vektor eigen yang terkait dengan nilai eigen nol (solusi bebas linear)
print("Solusi bebas linear (vektor eigen yang terkait dengan nilai eigen nol):")
print(zero_eigen_vector)

Solusi bebas linear (vektor eigen yang terkait dengan nilai eigen nol):
[[0.54120099]
 [0.55865908]
 [0.62849147]]


LATIHAN 2

In [ ]:
import numpy as np
# Definisikan matriks input-output Leontief E (pastikan ukuran dan isinya relevan)
E = np.array([[0,0.2,0.5], [1, 0.2,0.5],[0,0.6,0]])

#A=I-E
# Definisikan matriks A
A = np.array([[1,-0.2,-0.5], [-1, 0.8,-0.5],[0,-0.6,1]])

# Lakukan SVD pada matriks A
U, S, VT = np.linalg.svd(A)

# Matriks diagonal dari nilai singular dalam bentuk vektor
# Hasil SVD berupa U, nilai singular dalam bentuk diagonal dalam S, dan VT (V Transpose)
print("Matriks U:")
print(U)
print("\nMatriks Singular Values:")
print(np.diag(S))
print("\nMatriks V Transpose:")
print(VT)

#Setelah dilakukan SVD, temukan nilai-nilai singular yang mendekati nol
tolerance = 1e-10  # Ambang batas untuk nilai-nilai yang dianggap nol

# Cek nilai-nilai singular yang mendekati nol
zero_singular_values = np.where(S < tolerance)[0]

# Temukan vektor-vektor non-trivial dari matriks VT (V transpos)
if len(zero_singular_values) > 0:
    non_trivial_solution = VT[zero_singular_values[0]]
    print("Solusi non-trivial ditemukan:")
    print(abs(non_trivial_solution))
else:
    print("Tidak ada solusi non-trivial untuk Ax = 0.")

Matriks U:
[[-0.3698934  -0.7279049   0.57735027]
 [ 0.81533083  0.04361537  0.57735027]
 [-0.44543743  0.68428953  0.57735027]]

Matriks Singular Values:
[[1.68470855e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.30451412e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.57496097e-16]]

Matriks V Transpose:
[[-0.70351886  0.58971969 -0.39660044]
 [-0.59142347 -0.17638785  0.78683264]
 [-0.3940552  -0.78811041 -0.47286624]]
Solusi non-trivial ditemukan:
[0.3940552  0.78811041 0.47286624]


In [ ]:
P=np.array([[0.3940552, 0.78811041, 0.47286624]])
s= 100
print (P*s)

[[39.40552  78.811041 47.286624]]


## MODEL TERBUKA (PRODUKSI) LEONTIEF

In [ ]:
import numpy as np
from sympy import *

In [ ]:
def leontief_terbuka():

  print("Model Terbuka (Produksi) Leontief")
  print("1. Mencari Vektor Produksi (x)")
  print("2. Mencari Vektor Permintaan (d)")
  print("3. Periksa Matriks Konsumsi Produktif (C)")

  pil = int(input("Pilihan: "))

  n = int(input("Masukkan jumlah variabel: "))

  x = np.zeros(n)
  d = np.zeros(n)
  C = np.zeros((n,n))
  I = np.identity(n)

  if pil == 1:
    print("\n")
    for i in range(n):
      for j in range(n):
        C[i,j] = float(input(f"Masukkan entri matriks ke-[{i+1},{j+1}]: "))
    print("\n")

    for i in range(n):
      d[i] = float(input(f"Masukkan entri ke-{i+1} vektor permintaan: "))
    print("\n")

    hitung_x = np.dot(np.linalg.inv(I-C),d)
    print(f"Matriks Konsumsi (C) = \n {C} \n")
    print(f"Vektor Permintaan (d) = \n {d} \n")
    print(f"Perhitungan (I-C) = \n {I-C} \n")
    print(f"Vektor Produksi (x) = \n {hitung_x} \n")
  elif pil == 2:
    for i in range(n):
      x[i] = float(input(f"Masukkan entri ke-{i+1} vektor produksi: "))
    print("\n")

    for i in range(n):
      for j in range(n):
        C[i,j] = float(input(f"Masukkan entri matriks ke-[{i+1},{j+1}]: "))
    print("\n")

    hitung_d = np.dot((I-C),x)
    print(f"Matriks Konsumsi  = \n {C} \n")
    print(f"Vektor Produksi (x) = \n {x} \n")
    print(f"Perhitungan (I-C) = \n {I-C} \n")
    print(f"Vektor Permintaan (d) = \n {hitung_d}")
  elif pil == 3:
    def is_productive_matrix(C):
      num_sectors = C.shape[0]

      # Inisialisasi vektor produksi x
      x = np.ones(num_sectors)

      # Jumlah iterasi yang diinginkan
      max_iterations = 100

      # Batas toleransi untuk konvergensi
      tolerance = 1e-6

      for iteration in range(max_iterations):
        x_new = np.zeros(num_sectors)

        # Iterasi Jacobi
        for i in range(num_sectors):
          sum_Cx = np.dot(C[i, :], x) - C[i, i] * x[i]
          x_new[i] = 1 + sum_Cx

          # Memeriksa ketidaksetaraan x > Cx
        if np.all(x_new > x):
          return True, x_new

        x = x_new

      return False, None


    def cek_korolari(C):
      # Mengecek korolari jumlah baris
      korolari_baris = all(np.sum(C, axis=1) < 1)

      # Mengecek korolari jumlah kolom
      korolari_kolom = all(np.sum(C, axis=0) < 1)

      if korolari_baris and korolari_kolom:
        return "Matriks konsumsi memenuhi korolari jumlah baris dan jumlah kolom."
      elif korolari_baris:
        return "Matriks konsumsi memenuhi korolari jumlah baris."
      elif korolari_kolom:
        return "Matriks konsumsi memenuhi korolari jumlah kolom."
      else:
        return "Matriks konsumsi tidak memenuhi korolari jumlah baris maupun jumlah kolom."

    print("\n")
    for i in range(n):
      for j in range(n):
        C[i,j] = float(input(f"Masukkan entri matriks ke-[{i+1},{j+1}]: "))
    print("\n")

    # Cek apakah matriks konsumsi tersebut produktif
    is_productive, production_vector = is_productive_matrix(C)

    if is_productive:
      print(f"Matriks Konsumsi  = \n {C} \n")
      print("Matriks konsumsi adalah produktif.")
      print("Vektor produksi (x) yang memenuhi ketidaksetaraan:")
      print(production_vector)
      print("Hasil perhitungan Cx:")
      print(np.dot(C,production_vector))
      print(cek_korolari(C))

    else:
      print("Matriks konsumsi bukan matriks produktif.")
  else:
    print("\nPilihan tidak tersedia, silakan coba kembali")
    leontief_terbuka()

Contoh

Vektor Produksi untuk Sebuah Kota

In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 1
Masukkan jumlah variabel: 3


Masukkan entri matriks ke-[1,1]: 0
Masukkan entri matriks ke-[1,2]: 0.65
Masukkan entri matriks ke-[1,3]: 0.55
Masukkan entri matriks ke-[2,1]: 0.25
Masukkan entri matriks ke-[2,2]: 0.05
Masukkan entri matriks ke-[2,3]: 0.10
Masukkan entri matriks ke-[3,1]: 0.25
Masukkan entri matriks ke-[3,2]: 0.05
Masukkan entri matriks ke-[3,3]: 0


Masukkan entri ke-1 vektor permintaan: 50000
Masukkan entri ke-2 vektor permintaan: 25000
Masukkan entri ke-3 vektor permintaan: 0


Matriks Konsumsi (C) = 
 [[0.   0.65 0.55]
 [0.25 0.05 0.1 ]
 [0.25 0.05 0.  ]] 

Vektor Permintaan (d) = 
 [50000. 25000.     0.] 

Perhitungan (I-C) = 
 [[ 1.   -0.65 -0.55]
 [-0.25  0.95 -0.1 ]
 [-0.25 -0.05  1.  ]] 

Vektor Produksi (x) = 
 [102087.47514911  56163.02186879  28330.01988072] 



Contoh

Matriks Konsumsi Produktif

In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 3
Masukkan jumlah variabel: 3


Masukkan entri matriks ke-[1,1]: 0
Masukkan entri matriks ke-[1,2]: 0.65
Masukkan entri matriks ke-[1,3]: 0.55
Masukkan entri matriks ke-[2,1]: 0.25
Masukkan entri matriks ke-[2,2]: 0.05
Masukkan entri matriks ke-[2,3]: 0.10
Masukkan entri matriks ke-[3,1]: 0.25
Masukkan entri matriks ke-[3,2]: 0.05
Masukkan entri matriks ke-[3,3]: 0


Matriks Konsumsi  = 
 [[0.   0.65 0.55]
 [0.25 0.05 0.1 ]
 [0.25 0.05 0.  ]] 

Matriks konsumsi adalah produktif.
Vektor produksi (x) yang memenuhi ketidaksetaraan:
[2.2  1.35 1.3 ]
Hasil perhitungan Cx:
[1.5925 0.7475 0.6175]
Matriks konsumsi memenuhi korolari jumlah kolom.


Contoh

Mencari Vektor Permintaan

In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 2
Masukkan jumlah variabel: 3
Masukkan entri ke-1 vektor produksi: 10000
Masukkan entri ke-2 vektor produksi: 5000
Masukkan entri ke-3 vektor produksi: 5000


Masukkan entri matriks ke-[1,1]: 0.4
Masukkan entri matriks ke-[1,2]: 0.3
Masukkan entri matriks ke-[1,3]: 0.25
Masukkan entri matriks ke-[2,1]: 0.2
Masukkan entri matriks ke-[2,2]: 0.2
Masukkan entri matriks ke-[2,3]: 0.25
Masukkan entri matriks ke-[3,1]: 0.1
Masukkan entri matriks ke-[3,2]: 0.2
Masukkan entri matriks ke-[3,3]: 0.25


Matriks Konsumsi  = 
 [[0.4  0.3  0.25]
 [0.2  0.2  0.25]
 [0.1  0.2  0.25]] 

Vektor Produksi (x) = 
 [10000.  5000.  5000.] 

Perhitungan (I-C) = 
 [[ 0.6  -0.3  -0.25]
 [-0.2   0.8  -0.25]
 [-0.1  -0.2   0.75]] 

Vektor Permintaan (d) = 
 [3250.  750. 1750.]


Latihan Nomor 2

In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 3
Masukkan jumlah variabel: 2


Masukkan entri matriks ke-[1,1]: 0.8
Masukkan entri matriks ke-[1,2]: 0.1
Masukkan entri matriks ke-[2,1]: 0.3
Masukkan entri matriks ke-[2,2]: 0.6


Matriks Konsumsi  = 
 [[0.8 0.1]
 [0.3 0.6]] 

Matriks konsumsi adalah produktif.
Vektor produksi (x) yang memenuhi ketidaksetaraan:
[1.1 1.3]
Hasil perhitungan Cx:
[1.01 1.11]
Matriks konsumsi memenuhi korolari jumlah baris.


In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 3
Masukkan jumlah variabel: 3


Masukkan entri matriks ke-[1,1]: 0.70
Masukkan entri matriks ke-[1,2]: 0.30
Masukkan entri matriks ke-[1,3]: 0.25
Masukkan entri matriks ke-[2,1]: 0.20
Masukkan entri matriks ke-[2,2]: 0.40
Masukkan entri matriks ke-[2,3]: 0.25
Masukkan entri matriks ke-[3,1]: 0.05
Masukkan entri matriks ke-[3,2]: 0.15
Masukkan entri matriks ke-[3,3]: 0.25


Matriks Konsumsi  = 
 [[0.7  0.3  0.25]
 [0.2  0.4  0.25]
 [0.05 0.15 0.25]] 

Matriks konsumsi adalah produktif.
Vektor produksi (x) yang memenuhi ketidaksetaraan:
[1.55 1.45 1.2 ]
Hasil perhitungan Cx:
[1.82  1.19  0.595]
Matriks konsumsi memenuhi korolari jumlah kolom.


In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 3
Masukkan jumlah variabel: 3


Masukkan entri matriks ke-[1,1]: 0.7
Masukkan entri matriks ke-[1,2]: 0.3
Masukkan entri matriks ke-[1,3]: 0.2
Masukkan entri matriks ke-[2,1]: 0.1
Masukkan entri matriks ke-[2,2]: 0.4
Masukkan entri matriks ke-[2,3]: 0.3
Masukkan entri matriks ke-[3,1]: 0.2
Masukkan entri matriks ke-[3,2]: 0.4
Masukkan entri matriks ke-[3,3]: 0.1


Matriks Konsumsi  = 
 [[0.7 0.3 0.2]
 [0.1 0.4 0.3]
 [0.2 0.4 0.1]] 

Matriks konsumsi adalah produktif.
Vektor produksi (x) yang memenuhi ketidaksetaraan:
[1.5 1.4 1.6]
Hasil perhitungan Cx:
[1.79 1.19 1.02]
Matriks konsumsi tidak memenuhi korolari jumlah baris maupun jumlah kolom.


Latihan
Nomor 5

In [ ]:
leontief_terbuka()

Model Terbuka (Produksi) Leontief
1. Mencari Vektor Produksi (x)
2. Mencari Vektor Permintaan (d)
3. Periksa Matriks Konsumsi Produktif (C)
Pilihan: 1
Masukkan jumlah variabel: 3


Masukkan entri matriks ke-[1,1]: 0
Masukkan entri matriks ke-[1,2]: 0.2
Masukkan entri matriks ke-[1,3]: 0.3
Masukkan entri matriks ke-[2,1]: 0.1
Masukkan entri matriks ke-[2,2]: 0
Masukkan entri matriks ke-[2,3]: 0.4
Masukkan entri matriks ke-[3,1]: 0.3
Masukkan entri matriks ke-[3,2]: 0.4
Masukkan entri matriks ke-[3,3]: 0


Masukkan entri ke-1 vektor permintaan: 500
Masukkan entri ke-2 vektor permintaan: 700
Masukkan entri ke-3 vektor permintaan: 600


Matriks Konsumsi (C) = 
 [[0.  0.2 0.3]
 [0.1 0.  0.4]
 [0.3 0.4 0. ]] 

Vektor Permintaan (d) = 
 [500. 700. 600.] 

Perhitungan (I-C) = 
 [[ 1.  -0.2 -0.3]
 [-0.1  1.  -0.4]
 [-0.3 -0.4  1. ]] 

Vektor Produksi (x) = 
 [1256.48414986 1448.12680115 1556.19596542] 

